### PR TITLE
Add airbrake adapter

### PR DESCRIPTION
**Pull request by ostap0207**
Move changes from
https://github.com/salemove/message-hub/commit/6f49f5dfbada3ec45869e9cab01e09153d4068f2
to a separate airbrake adapter

EN-495

### CODE REVIEW

**Comment by urmastalimaa** [comment]
+1!

**Comment by indrekj** [comment]
I don't like this change. This change adds a dependency to this package. If we want to keep it open source and like to see anyone using this package then we can't just add random dependencies. Would it make sense to create `node-logasm-airbrake` package which is an extension to this package? Or some other way load the dependency dynamically.

**Comment by ostap0207** [comment]
So is logasm just a wrapper for logstash and nothing else? The previous version is still will be available, also do we know if there are a lot of people out of salemove using it. Just don't understand the point to keep it as is just for people to use, which limits us. I guess would be better if there was a way to add an adapter or load the dependency dynamically.

**Comment by indrekj** [comment]
There probably aren't any but if we ever want to contribute to open source then we have to start thinking about it. Also, maybe we don't have to reimplement it. Maybe we can just add https://github.com/shakefon/winston-airbrake middleware. 

By looking node-logasm code then maybe we can replace it with https://www.npmjs.com/package/winston-logstash-udp or something similar.

I'd rather see our custom adapters for winston than a wrapper on winston. This way other people can use it as well and it is much more flexible.

**Comment by ostap0207** [comment]
If `node-logasm` just a small wrapper around winston there is not much point of open sourcing it. But even if we still want to open source it we need to make it extendable same as `winston` and move current adapters to separate modules and release version 1.

I agree that we need to think about it, maybe let's create a ticket for it. But it's a bit out of scope for this PR.

**Comment by ostap0207** [comment]
Talked with @indrekj and decided see if we could replace 'logasm' with `winston` and use winston adapters for airbrake and logstash.

**Comment by indrekj** [comment]
@ostap0207 if you replace all other occurrences as well then lets please nuke this repository. Closing for now.

**Pull request closed without merging**
