### PR TITLE
Add timestamp to logstash messages

### PR DESCRIPTION
**Pull request by indrekj**
Otherwise they get their timestamp in logstash which might be off
because of the network delay and processing time.

### CODE REVIEW

**Review by willmore — APPROVED** [review]

**Comment by ostap0207** [comment]
Is this for browser logs?

**Comment by indrekj** [comment]
No. This is whoever is using this library (message-hub in our case). Makes it similar with ruby logasm.

**Review by ostap0207 — APPROVED** [review]

**Comment by ostap0207** [comment]
Ok, I just saw that client logs also include the timestamp but it's not used.

**Comment by ostap0207** [comment]
!merge

**Pull request merged**
