### PR TITLE
Hello node-lenjador!

### PR DESCRIPTION
**Pull request by willmore**

### CODE REVIEW

**Comment by deiwin** [comment]
Please also include other people as NPM package collaborators. See e.g. https://www.npmjs.com/package/eslint-config-salemove

**Comment by deiwin** [comment]
Also, the repository name is yet to be updated here.

**Comment by deiwin** [comment]
This also has an SM account as a collaborator: https://www.npmjs.com/package/codo-theme-sm

**Comment by willmore** [comment]
Attempting to add collaborators, but hitting [this issue]( https://github.com/npm/npm/issues/20787).
Will update when possible.

**Comment by willmore** [comment]
`npm` issue cleared up. Collaborators added to package.

**Pull request merged**
